/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_api_accounts__account_id__patch"];
        trace?: never;
    };
    "/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Statements */
        get: operations["list_statements_api_statements_get"];
        put?: never;
        /**
         * Upload Statement
         * @description Multipart upload. `user_id` (D4: chosen in the Import screen, sticky) is a form field
         *     alongside `file`.
         */
        post: operations["upload_statement_api_statements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements/{statement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Statement */
        get: operations["get_statement_api_statements__statement_id__get"];
        put?: never;
        post?: never;
        /** Delete Statement */
        delete: operations["delete_statement_api_statements__statement_id__delete"];
        options?: never;
        head?: never;
        /** Patch Statement */
        patch: operations["patch_statement_api_statements__statement_id__patch"];
        trace?: never;
    };
    "/statements/{statement_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Statement Page
         * @description One page's words (`x0`/`x1`/`top`/`bottom`) plus page size, for the Layout mapper's
         *     click-to-map UI (§2c). Local-only: this stays on the token-protected localhost API and never
         *     goes through egress (I1b/I3).
         */
        get: operations["preview_statement_page_api_statements__statement_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements/{statement_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Statement
         * @description A22 phase 2: enqueues an `import` job that calls `confirm_import`, then (job flow, P2-C
         *     plan section) enqueues a `classify` job for the transactions it inserted.
         */
        post: operations["extract_statement_api_statements__statement_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements/{statement_id}/reparse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reparse Statement */
        post: operations["reparse_statement_api_statements__statement_id__reparse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Transaction */
        patch: operations["patch_transaction_api_transactions__id__patch"];
        trace?: never;
    };
    "/transactions/bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Update Transactions */
        post: operations["bulk_update_transactions_api_transactions_bulk_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classify/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Classify */
        post: operations["run_classify_api_classify_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classify/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Classify
         * @description The exact CSV the next run would send (A5), decoded back into rows. No network call.
         */
        get: operations["preview_classify_api_classify_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classify/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Classify Runs */
        get: operations["list_classify_runs_api_classify_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Summary */
        get: operations["analytics_summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Timeseries */
        get: operations["analytics_timeseries_api_analytics_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/top-merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Top Merchants */
        get: operations["analytics_top_merchants_api_analytics_top_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Taxonomy */
        get: operations["get_taxonomy_api_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy/subcategories/{subcategory_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Subcategory */
        post: operations["approve_subcategory_api_taxonomy_subcategories__subcategory_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy/subcategories/{subcategory_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Subcategory */
        post: operations["merge_subcategory_api_taxonomy_subcategories__subcategory_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issuers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Issuers */
        get: operations["list_issuers_api_issuers_get"];
        put?: never;
        /** Create Issuer */
        post: operations["create_issuer_api_issuers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issuers/{issuer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Issuer */
        delete: operations["delete_issuer_api_issuers__issuer_id__delete"];
        options?: never;
        head?: never;
        /** Update Issuer */
        patch: operations["update_issuer_api_issuers__issuer_id__patch"];
        trace?: never;
    };
    "/issuers/preview-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Issuer Match
         * @description A dry run for A24: which existing statements `body.match_terms` would match, before
         *     saving them to a real issuer (never writes anything; never returns page text).
         */
        post: operations["preview_issuer_match_api_issuers_preview_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout-specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Layout Specs */
        get: operations["list_layout_specs_api_layout_specs_get"];
        put?: never;
        /** Create Layout Spec */
        post: operations["create_layout_spec_api_layout_specs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout-specs/{spec_id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Layout Spec */
        post: operations["revise_layout_spec_api_layout_specs__spec_id__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout-specs/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry Run Layout Spec
         * @description Parse `body.statement_id`'s staged PDF with `body.spec_yaml`, without writing anything to
         *     the database (§2c's own "try before you save" workflow) — the Layout mapper's own preview.
         */
        post: operations["dry_run_layout_spec_api_layout_specs_dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout-specs/{spec_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Layout Spec */
        post: operations["approve_layout_spec_api_layout_specs__spec_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout-specs/{spec_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Layout Spec */
        get: operations["export_layout_spec_api_layout_specs__spec_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_api_rules__rule_id__patch"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings Route */
        get: operations["get_settings_route_api_settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Api Key
         * @description Store `body.api_key` for `body.provider` in the OS keychain (I7). Never returned, logged,
         *     or written to `config.toml`/the database — `body` itself is never included in any response.
         */
        put: operations["put_api_key_api_settings_api_key_put"];
        post?: never;
        /**
         * Delete Api Key Route
         * @description Remove `provider`'s key from the OS keychain, if present (I7). Idempotent: clearing an
         *     already-absent key is not an error.
         */
        delete: operations["delete_api_key_route_api_settings_api_key_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/test-llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Llm Settings
         * @description One-row round trip verifying credentials, via the same `classify_batch` egress path every
         *     real classification uses (never a bespoke LLM call).
         */
        post: operations["test_llm_settings_api_settings_test_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Transactions
         * @description Export every transaction, or (with `user_id`) just one user's, oldest first. The CLI's
         *     `export --user-id`/`--all-users` call this directly with a resolved id or `None`; the HTTP
         *     route itself leaves `user_id` unset by default (exports everything).
         */
        get: operations["export_transactions_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Issuer Id */
            issuer_id: number | null;
            /**
             * Account Type
             * @enum {string}
             */
            account_type: "credit" | "checking" | "savings";
            /** Currency */
            currency: string;
        };
        /** AccountCreate */
        AccountCreate: {
            /** User Id */
            user_id: number;
            /** Issuer Id */
            issuer_id?: number | null;
            /**
             * Account Type
             * @enum {string}
             */
            account_type: "credit" | "checking" | "savings";
            /**
             * Mask
             * @default
             */
            mask: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
        };
        /** AccountUpdate */
        AccountUpdate: {
            /** Issuer Id */
            issuer_id?: number | null;
            /** Account Type */
            account_type?: ("credit" | "checking" | "savings") | null;
            /** Mask */
            mask?: string | null;
            /** Currency */
            currency?: string | null;
        };
        /** AnalyticsRow */
        AnalyticsRow: {
            /** Period */
            period?: string | null;
            /** Category */
            category?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** User */
            user?: number | null;
            /** Account */
            account?: number | null;
            /** Merchant */
            merchant?: string | null;
            /** Currency */
            currency: string;
            /** Total Minor */
            total_minor: number;
            /** Txn Count */
            txn_count: number;
            /** Avg Minor */
            avg_minor: number;
        };
        /**
         * ApiKeyPut
         * @description `PUT /api/settings/api-key` body (I7: the key is written straight to the OS keychain via
         *     `config.set_api_key` — never to `config.toml`, the database, a response, or a log line).
         */
        ApiKeyPut: {
            /** Provider */
            provider: string;
            /** Api Key */
            api_key: string;
        };
        /** Body_upload_statement_api_statements_post */
        Body_upload_statement_api_statements_post: {
            /** File */
            file: string;
            /** User Id */
            user_id: number;
        };
        /** BulkUpdateRequest */
        BulkUpdateRequest: {
            /** Transaction Ids */
            transaction_ids: number[];
            /** Category Key */
            category_key?: string | null;
            /** Subcategory Key */
            subcategory_key?: string | null;
            kind?: components["schemas"]["Kind"] | null;
        };
        /** BulkUpdateResponse */
        BulkUpdateResponse: {
            /** Updated */
            updated: number;
        };
        /** Category */
        Category: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Subcategories */
            subcategories: components["schemas"]["Subcategory"][];
        };
        /** ClassifyPreviewRow */
        ClassifyPreviewRow: {
            /** Merchant Key */
            merchant_key: string;
            /** Description Clean */
            description_clean: string;
        };
        /** ClassifyRunRequest */
        ClassifyRunRequest: {
            /** User Id */
            user_id?: number | null;
            /** Statement Id */
            statement_id?: number | null;
            /**
             * Only Unclassified
             * @default true
             */
            only_unclassified: boolean;
        };
        /** ClassifyRunResponse */
        ClassifyRunResponse: {
            /** Job Id */
            job_id: string;
            /** Group Id */
            group_id: string;
        };
        /** ExtractRequest */
        ExtractRequest: {
            /** Issuer Id */
            issuer_id: number;
            /** Layout Spec Id */
            layout_spec_id?: number | null;
            /** Parser Id */
            parser_id?: string | null;
            /**
             * Remember
             * @default false
             */
            remember: boolean;
        };
        /** ExtractorProposal */
        ExtractorProposal: {
            /** Issuer Id */
            issuer_id: number | null;
            /** Parser Id */
            parser_id: string | null;
            /** Layout Spec Id */
            layout_spec_id: number | null;
            /** Confidence */
            confidence: number;
            /** Auto Confirmed */
            auto_confirmed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestSettings */
        IngestSettings: {
            /** Always Confirm Extractor */
            always_confirm_extractor: boolean;
            /** Date Format Hints */
            date_format_hints: string[];
            /** Default Currency */
            default_currency: string;
        };
        /** Issuer */
        Issuer: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Match Terms */
            match_terms: string[];
            /** Default Spec Id */
            default_spec_id?: number | null;
        };
        /** IssuerCreate */
        IssuerCreate: {
            /** Name */
            name: string;
            /** Match Terms */
            match_terms?: string[];
        };
        /** IssuerMatchPreviewRequest */
        IssuerMatchPreviewRequest: {
            /** Match Terms */
            match_terms: string[];
        };
        /** IssuerMatchPreviewRow */
        IssuerMatchPreviewRow: {
            /** Statement Id */
            statement_id: number;
            /** Original Name */
            original_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "awaiting_extractor" | "parsed" | "no_text_layer" | "unsupported_layout" | "error";
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
        };
        /** IssuerUpdate */
        IssuerUpdate: {
            /** Name */
            name?: string | null;
            /** Match Terms */
            match_terms?: string[] | null;
            /** Default Spec Id */
            default_spec_id?: number | null;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "import" | "classify";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error" | "cancelled";
            /** Progress */
            progress: number;
            /** Message */
            message?: string | null;
            /** Group Id */
            group_id?: string | null;
            /** Error Detail */
            error_detail?: string | null;
            /** Classify Job Id */
            classify_job_id?: string | null;
            /** Classified */
            classified?: number | null;
            /** Needs Review */
            needs_review?: number | null;
        };
        /** JobIdResponse */
        JobIdResponse: {
            /** Job Id */
            job_id: string;
        };
        /**
         * Kind
         * @description The seven `Kind` values (§3.1), as a real enum rather than a `Literal` alias: FastAPI
         *     only emits a named, reusable `components.schemas.Kind` in the OpenAPI document (which the
         *     frontend's generated client references as `components["schemas"]["Kind"]`) for an enum type
         *     — a `Literal` field is inlined per-field instead.
         * @enum {string}
         */
        Kind: "purchase" | "refund" | "payment" | "transfer" | "fee" | "interest" | "adjustment";
        /** LayoutSpec */
        LayoutSpec: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Issuer Id */
            issuer_id: number | null;
            /** Approved */
            approved: boolean;
            /** Source */
            source: string;
        };
        /** LayoutSpecCreate */
        LayoutSpecCreate: {
            /** Name */
            name: string;
            /** Spec Yaml */
            spec_yaml: string;
            /** Issuer Id */
            issuer_id?: number | null;
        };
        /** LayoutSpecDryRunRequest */
        LayoutSpecDryRunRequest: {
            /** Statement Id */
            statement_id: number;
            /** Spec Yaml */
            spec_yaml: string;
        };
        /** LayoutSpecDryRunResponse */
        LayoutSpecDryRunResponse: {
            /** Txn Count */
            txn_count: number;
            /** Total Minor */
            total_minor: number;
            /** Currency */
            currency: string;
            /** Sample Rows */
            sample_rows: components["schemas"]["LayoutSpecDryRunRow"][];
            /** Warnings */
            warnings: string[];
            /** Reconciliation Delta Minor */
            reconciliation_delta_minor?: number | null;
        };
        /** LayoutSpecDryRunRow */
        LayoutSpecDryRunRow: {
            /** Description Clean */
            description_clean: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Amount Minor */
            amount_minor: number;
        };
        /** LlmRun */
        LlmRun: {
            /** Id */
            id: number;
            /** Group Id */
            group_id: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Schema Mode */
            schema_mode: string;
            /** Cost Usd */
            cost_usd: number | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LlmSettings */
        LlmSettings: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "none" | "local" | "remote";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Api Base */
            api_base: string;
            /** Batch Size */
            batch_size: number;
            /** Timeout S */
            timeout_s: number;
            /** Confidence Threshold */
            confidence_threshold: number;
            /**
             * Has Key
             * @default false
             */
            has_key: boolean;
        };
        /** MergeRequest */
        MergeRequest: {
            /** Into Id */
            into_id: number;
        };
        /** PrivacySettings */
        PrivacySettings: {
            /** Store Pdf Copies */
            store_pdf_copies: boolean;
            /** Store Extract Cache */
            store_extract_cache: boolean;
            /** Pii Terms */
            pii_terms: string[];
        };
        /** Rule */
        Rule: {
            /** Id */
            id: number;
            /** Pattern */
            pattern: string;
            /** Category Key */
            category_key: string;
            /** Subcategory Key */
            subcategory_key: string;
            kind?: components["schemas"]["Kind"] | null;
            /** Source */
            source: string;
        };
        /** RuleCreate */
        RuleCreate: {
            /** Pattern */
            pattern: string;
            /**
             * Match Type
             * @default contains
             * @enum {string}
             */
            match_type: "exact" | "contains" | "regex";
            /** Category Key */
            category_key: string;
            /** Subcategory Key */
            subcategory_key: string;
            kind?: components["schemas"]["Kind"] | null;
        };
        /** RuleUpdate */
        RuleUpdate: {
            /** Pattern */
            pattern?: string | null;
            /** Category Key */
            category_key?: string | null;
            /** Subcategory Key */
            subcategory_key?: string | null;
            kind?: components["schemas"]["Kind"] | null;
        };
        /** ServerSettings */
        ServerSettings: {
            /** Port */
            port: number;
        };
        /** Settings */
        Settings: {
            llm: components["schemas"]["LlmSettings"];
            privacy: components["schemas"]["PrivacySettings"];
            ingest: components["schemas"]["IngestSettings"];
            server: components["schemas"]["ServerSettings"];
        };
        /** Statement */
        Statement: {
            /** Id */
            id: number;
            /** User Id */
            user_id?: number | null;
            /** Account Id */
            account_id: number | null;
            /** Issuer Id */
            issuer_id?: number | null;
            /** Parser Id */
            parser_id?: string | null;
            /** Layout Spec Id */
            layout_spec_id?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "awaiting_extractor" | "parsed" | "no_text_layer" | "unsupported_layout" | "error";
            /** Period Start */
            period_start: string | null;
            /** Period End */
            period_end: string | null;
            /** Txn Count */
            txn_count: number | null;
            /** Reconciliation Delta Minor */
            reconciliation_delta_minor?: number | null;
            /** Detect Score */
            detect_score: number | null;
            /** Shape Warnings */
            shape_warnings: string | null;
            /** Error Detail */
            error_detail: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StatementPatch */
        StatementPatch: {
            /** User Id */
            user_id?: number | null;
            /** Account Id */
            account_id?: number | null;
        };
        /** StatementPreviewPage */
        StatementPreviewPage: {
            /** Page Number */
            page_number: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Words */
            words: components["schemas"]["StatementPreviewWord"][];
        };
        /** StatementPreviewWord */
        StatementPreviewWord: {
            /** Text */
            text: string;
            /** X0 */
            x0: number;
            /** X1 */
            x1: number;
            /** Top */
            top: number;
            /** Bottom */
            bottom: number;
        };
        /** StatementUploadResponse */
        StatementUploadResponse: {
            statement: components["schemas"]["Statement"];
            proposal: components["schemas"]["ExtractorProposal"];
        };
        /** Subcategory */
        Subcategory: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Pending */
            pending: boolean;
            /** Merged Into */
            merged_into?: string | null;
        };
        /** TestLlmResponse */
        TestLlmResponse: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** TopMerchantRow */
        TopMerchantRow: {
            /** Merchant */
            merchant: string;
            /** Total Minor */
            total_minor: number;
            /** Txn Count */
            txn_count: number;
        };
        /** Transaction */
        Transaction: {
            /** Id */
            id: number;
            /** Statement Id */
            statement_id: number;
            /** Account Id */
            account_id: number;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Transaction Date */
            transaction_date: string | null;
            /** Description Raw */
            description_raw: string;
            /** Description Clean */
            description_clean: string;
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
            kind: components["schemas"]["Kind"];
            /** Category Key */
            category_key: string | null;
            /** Subcategory Key */
            subcategory_key: string | null;
            /** Merchant Key */
            merchant_key: string | null;
            /** Notes */
            notes: string | null;
            /** Needs Review */
            needs_review: boolean;
        };
        /** TransactionList */
        TransactionList: {
            /** Items */
            items: components["schemas"]["Transaction"][];
            /** Total */
            total: number;
        };
        /** TransactionPatch */
        TransactionPatch: {
            /** Category Key */
            category_key?: string | null;
            /** Subcategory Key */
            subcategory_key?: string | null;
            kind?: components["schemas"]["Kind"] | null;
            /** Notes */
            notes?: string | null;
            /**
             * Create Rule
             * @default false
             */
            create_rule: boolean;
        };
        /** User */
        User: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Is Default */
            is_default: boolean;
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    create_account_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_statements_api_statements_get: {
        parameters: {
            query?: {
                user_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statement"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_statement_api_statements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_statement_api_statements_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_statement_api_statements__statement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_statement_api_statements__statement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_statement_api_statements__statement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatementPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_statement_page_api_statements__statement_id__preview_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                statement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementPreviewPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_statement_api_statements__statement_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobIdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reparse_statement_api_statements__statement_id__reparse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobIdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_transactions_get: {
        parameters: {
            query?: {
                user_ids?: number[] | null;
                account_ids?: number[] | null;
                statement_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                category_keys?: string[] | null;
                subcategory_keys?: string[] | null;
                amount_min_minor?: number | null;
                amount_max_minor?: number | null;
                kinds?: components["schemas"]["Kind"][] | null;
                include_non_spend?: boolean;
                needs_review?: boolean | null;
                search?: string | null;
                currency?: string;
                page?: number;
                page_size?: number;
                sort?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_transaction_api_transactions__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_transactions_api_transactions_bulk_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_classify_api_classify_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_classify_api_classify_preview_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                statement_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyPreviewRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_classify_runs_api_classify_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmRun"][];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_summary_api_analytics_summary_get: {
        parameters: {
            query?: {
                user_ids?: number[] | null;
                account_ids?: number[] | null;
                date_from?: string | null;
                date_to?: string | null;
                granularity?: "day" | "week" | "month" | "quarter" | "year" | "all";
                group_by?: ("category" | "subcategory" | "user" | "account" | "merchant" | "period")[] | null;
                category_keys?: string[] | null;
                subcategory_keys?: string[] | null;
                amount_min_minor?: number | null;
                amount_max_minor?: number | null;
                kinds?: components["schemas"]["Kind"][] | null;
                include_non_spend?: boolean;
                net_refunds?: boolean;
                search?: string | null;
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_timeseries_api_analytics_timeseries_get: {
        parameters: {
            query?: {
                user_ids?: number[] | null;
                account_ids?: number[] | null;
                date_from?: string | null;
                date_to?: string | null;
                granularity?: "day" | "week" | "month" | "quarter" | "year" | "all";
                group_by?: ("category" | "subcategory" | "user" | "account" | "merchant" | "period")[] | null;
                category_keys?: string[] | null;
                subcategory_keys?: string[] | null;
                kinds?: components["schemas"]["Kind"][] | null;
                include_non_spend?: boolean;
                net_refunds?: boolean;
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_top_merchants_api_analytics_top_merchants_get: {
        parameters: {
            query?: {
                user_ids?: number[] | null;
                account_ids?: number[] | null;
                date_from?: string | null;
                date_to?: string | null;
                category_keys?: string[] | null;
                currency?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMerchantRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taxonomy_api_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    approve_subcategory_api_taxonomy_subcategories__subcategory_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subcategory_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subcategory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_subcategory_api_taxonomy_subcategories__subcategory_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subcategory_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subcategory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_issuers_api_issuers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issuer"][];
                };
            };
        };
    };
    create_issuer_api_issuers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issuer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_issuer_api_issuers__issuer_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issuer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_issuer_api_issuers__issuer_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issuer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issuer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_issuer_match_api_issuers_preview_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuerMatchPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuerMatchPreviewRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_layout_specs_api_layout_specs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpec"][];
                };
            };
        };
    };
    create_layout_spec_api_layout_specs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutSpecCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_layout_spec_api_layout_specs__spec_id__revise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spec_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutSpecCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dry_run_layout_spec_api_layout_specs_dry_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutSpecDryRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpecDryRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_layout_spec_api_layout_specs__spec_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spec_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_layout_spec_api_layout_specs__spec_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spec_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    create_rule_api_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_route_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_api_key_api_settings_api_key_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_key_route_api_settings_api_key_delete: {
        parameters: {
            query: {
                provider: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_llm_settings_api_settings_test_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestLlmResponse"];
                };
            };
        };
    };
    export_transactions_api_export_get: {
        parameters: {
            query?: {
                format?: "csv" | "json";
                user_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
