/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatements"];
        put?: never;
        /** @description Multipart upload. A22 phase 1: text extracted, issuer matched, extractor proposed; status='awaiting_extractor'; nothing parsed yet. */
        post: operations["uploadStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["getStatement"];
        put?: never;
        post?: never;
        /** @description Cascades to transactions. */
        delete: operations["deleteStatement"];
        options?: never;
        head?: never;
        /** @description Reassign user/account (§3.5). */
        patch: operations["patchStatement"];
        trace?: never;
    };
    "/statements/{id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description A22 phase 2: parse + persist. */
        post: operations["extractStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements/{id}/reparse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Re-run with a different extractor (rebuilds that statement's rows). */
        post: operations["reparseStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Filters mirror SpendQuery; paginated, sortable. */
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Set category/subcategory/kind/notes → writes merchant_map(source='user'), optionally creates a rule. */
        patch: operations["patchTransaction"];
        trace?: never;
    };
    "/transactions/bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Apply one label to a filtered selection. */
        post: operations["bulkUpdateTransactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classify/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runClassify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classify/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The exact CSV that would be sent (NO network call). */
        get: operations["previewClassify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classify/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description llm_runs audit list w/ cost, tokens, model, schema_mode. */
        get: operations["listClassifyRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description SSE progress stream. The per-launch token is passed as a query parameter (A31), since EventSource cannot set headers. */
        get: operations["getJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalyticsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnalyticsTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/top-merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopMerchants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Categories + subcategories incl. pending. */
        get: operations["getTaxonomy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy/subcategories/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveSubcategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomy/subcategories/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mergeSubcategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issuers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIssuers"];
        put?: never;
        post: operations["createIssuer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issuers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteIssuer"];
        options?: never;
        head?: never;
        patch: operations["updateIssuer"];
        trace?: never;
    };
    "/layout-specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description list (name, version, issuer, approved, source). */
        get: operations["listLayoutSpecs"];
        put?: never;
        /** @description Create v1, or paste. */
        post: operations["createLayoutSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout-specs/{id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Inserts version+1 (never mutates). */
        post: operations["reviseLayoutSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout-specs/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approve a user-authored or pasted spec. */
        post: operations["approveLayoutSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layout-specs/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description YAML download. */
        get: operations["exportLayoutSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRules"];
        put?: never;
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch: operations["updateRule"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Never returns key material. */
        get: operations["getSettings"];
        /** @description Rewrites config.toml atomically (A4). */
        put: operations["putSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/test-llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description One-row round trip verifying credentials. */
        post: operations["testLlmSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Full transaction export — MUST exclude accounts.mask. */
        get: operations["exportTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            detail: string;
        };
        /** @example USD */
        Currency: string;
        /** @enum {string} */
        Kind: "purchase" | "refund" | "payment" | "transfer" | "fee" | "interest" | "adjustment";
        /** @enum {string} */
        AccountType: "credit" | "checking" | "savings";
        User: {
            id: number;
            name: string;
            is_default: boolean;
        };
        UserCreate: {
            name: string;
            is_default?: boolean;
        };
        UserUpdate: {
            name?: string;
            is_default?: boolean;
        };
        Account: {
            id: number;
            user_id: number;
            issuer_id: number | null;
            account_type: components["schemas"]["AccountType"];
            /** @description Last 4 digits only. LOCAL ONLY (I1b). */
            mask: string;
            currency: components["schemas"]["Currency"];
        };
        AccountCreate: {
            user_id: number;
            issuer_id?: number | null;
            account_type: components["schemas"]["AccountType"];
            mask?: string;
            currency: components["schemas"]["Currency"];
        };
        AccountUpdate: {
            issuer_id?: number | null;
            account_type?: components["schemas"]["AccountType"];
            mask?: string;
            currency?: components["schemas"]["Currency"];
        };
        /** @enum {string} */
        StatementStatus: "awaiting_extractor" | "queued" | "processing" | "done" | "error" | "no_text_layer" | "unsupported_layout";
        Statement: {
            id: number;
            user_id?: number | null;
            account_id?: number | null;
            status: components["schemas"]["StatementStatus"];
            /** Format: date */
            period_start?: string | null;
            /** Format: date */
            period_end?: string | null;
            txn_count?: number;
            /** @description Signed minor units; 0 when the balance equation reconciles exactly (§3.1 A25). */
            reconciliation_delta_minor?: number | null;
            detect_score?: number | null;
            shape_warnings?: string | null;
            error_detail?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ExtractorProposal: {
            issuer_id?: number | null;
            parser_id?: string | null;
            layout_spec_id?: number | null;
            confidence?: number;
            auto_confirmed?: boolean;
        };
        StatementUploadResponse: {
            statement: components["schemas"]["Statement"];
            proposal: components["schemas"]["ExtractorProposal"];
        };
        ExtractRequest: {
            issuer_id: number;
            layout_spec_id?: number | null;
            parser_id?: string | null;
            remember: boolean;
        };
        StatementPatch: {
            user_id?: number;
            account_id?: number;
        };
        Job: {
            id: string;
            /** @enum {string} */
            kind: "import" | "classify";
            /** @enum {string} */
            status: "queued" | "running" | "done" | "error";
            progress: number;
            message?: string | null;
            group_id?: string | null;
            error_detail?: string | null;
        };
        Transaction: {
            id: number;
            statement_id: number;
            account_id: number;
            /** Format: date */
            posted_date: string;
            /** Format: date */
            transaction_date?: string | null;
            description_clean: string;
            /** @description Signed minor units; positive = outflow (I5). */
            amount_minor: number;
            currency: components["schemas"]["Currency"];
            kind: components["schemas"]["Kind"];
            category_key: string | null;
            subcategory_key: string | null;
            merchant_key?: string | null;
            notes?: string | null;
            needs_review: boolean;
        };
        TransactionPatch: {
            category_key?: string;
            subcategory_key?: string;
            kind?: components["schemas"]["Kind"];
            notes?: string;
            create_rule?: boolean;
        };
        BulkUpdateRequest: {
            transaction_ids: number[];
            category_key?: string;
            subcategory_key?: string;
            kind?: components["schemas"]["Kind"];
        };
        ClassifyRunRequest: {
            user_id?: number | null;
            statement_id?: number | null;
            /** @default true */
            only_unclassified: boolean;
        };
        ClassifyRunResponse: {
            job_id: string;
            group_id: string;
        };
        ClassifyPreviewRow: {
            merchant_key?: string;
            description_clean?: string;
        };
        LlmRun: {
            id?: number;
            group_id?: string;
            provider?: string;
            model?: string;
            schema_mode?: string;
            cost_usd?: number | null;
            prompt_tokens?: number | null;
            completion_tokens?: number | null;
            /** Format: date-time */
            created_at?: string;
        };
        AnalyticsRow: {
            period?: string | null;
            category?: string | null;
            subcategory?: string | null;
            user?: string | null;
            account?: string | null;
            merchant?: string | null;
            currency: components["schemas"]["Currency"];
            total_minor: number;
            txn_count: number;
            avg_minor: number;
        };
        TopMerchantRow: {
            merchant?: string;
            total_minor?: number;
            txn_count?: number;
        };
        Subcategory: {
            key: string;
            name: string;
            pending: boolean;
            merged_into?: string | null;
        };
        Category: {
            key: string;
            name: string;
            subcategories: components["schemas"]["Subcategory"][];
        };
        MergeRequest: {
            into_id: string;
        };
        Issuer: {
            id: number;
            name: string;
            slug: string;
            match_terms: string[];
            default_spec_id?: number | null;
        };
        IssuerCreate: {
            name: string;
            match_terms?: string[];
        };
        IssuerUpdate: {
            name?: string;
            match_terms?: string[];
            default_spec_id?: number | null;
        };
        LayoutSpec: {
            id: number;
            name: string;
            version: number;
            issuer_id?: number | null;
            approved: boolean;
            /** @enum {string} */
            source: "hand_mapped" | "pasted";
        };
        LayoutSpecCreate: {
            name: string;
            spec_yaml: string;
            issuer_id?: number | null;
        };
        Rule: {
            id: number;
            pattern: string;
            category_key: string;
            subcategory_key: string;
            kind?: components["schemas"]["Kind"];
            /** @enum {string} */
            source?: "builtin" | "user";
        };
        RuleCreate: {
            pattern: string;
            category_key: string;
            subcategory_key: string;
            kind?: components["schemas"]["Kind"];
        };
        RuleUpdate: {
            pattern?: string;
            category_key?: string;
            subcategory_key?: string;
            kind?: components["schemas"]["Kind"];
        };
        /** @enum {string} */
        LlmMode: "none" | "local" | "remote";
        Settings: {
            llm?: {
                mode?: components["schemas"]["LlmMode"];
                provider?: string;
                model?: string;
                api_base?: string;
                batch_size?: number;
                timeout_s?: number;
                confidence_threshold?: number;
            };
            privacy?: {
                store_pdf_copies?: boolean;
                store_extract_cache?: boolean;
                pii_terms?: string[];
            };
            ingest?: {
                always_confirm_extractor?: boolean;
                date_format_hints?: string[];
                default_currency?: components["schemas"]["Currency"];
            };
            server?: {
                port?: number;
            };
        };
        TestLlmResponse: {
            ok: boolean;
            detail?: string | null;
        };
    };
    responses: never;
    parameters: {
        UserIds: number[];
        AccountIds: number[];
        DateFrom: string;
        DateTo: string;
        Granularity: "day" | "week" | "month" | "quarter" | "year" | "all";
        GroupBy: ("category" | "subcategory" | "user" | "account" | "merchant" | "period")[];
        CategoryKeys: string[];
        SubcategoryKeys: string[];
        AmountMinMinor: number;
        AmountMaxMinor: number;
        Kinds: components["schemas"]["Kind"][];
        IncludeNonSpend: boolean;
        NetRefunds: boolean;
        Search: string;
        Currency: string;
        Page: number;
        PageSize: number;
        Sort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    listStatements: {
        parameters: {
            query?: {
                user_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statement"][];
                };
            };
        };
    };
    uploadStatement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementUploadResponse"];
                };
            };
        };
    };
    getStatement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statement"];
                };
            };
        };
    };
    deleteStatement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchStatement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StatementPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statement"];
                };
            };
        };
    };
    extractStatement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job_id: string;
                    };
                };
            };
        };
    };
    reparseStatement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job_id: string;
                    };
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                user_ids?: components["parameters"]["UserIds"];
                account_ids?: components["parameters"]["AccountIds"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                category_keys?: components["parameters"]["CategoryKeys"];
                subcategory_keys?: components["parameters"]["SubcategoryKeys"];
                amount_min_minor?: components["parameters"]["AmountMinMinor"];
                amount_max_minor?: components["parameters"]["AmountMaxMinor"];
                kinds?: components["parameters"]["Kinds"];
                include_non_spend?: components["parameters"]["IncludeNonSpend"];
                search?: components["parameters"]["Search"];
                currency?: components["parameters"]["Currency"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Transaction"][];
                        total: number;
                    };
                };
            };
        };
    };
    patchTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TransactionPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    bulkUpdateTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulkUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        updated: number;
                    };
                };
            };
        };
    };
    runClassify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClassifyRunRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyRunResponse"];
                };
            };
        };
    };
    previewClassify: {
        parameters: {
            query?: {
                user_id?: number;
                statement_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyPreviewRow"][];
                };
            };
        };
    };
    listClassifyRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmRun"][];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    getJobEvents: {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getAnalyticsSummary: {
        parameters: {
            query?: {
                user_ids?: components["parameters"]["UserIds"];
                account_ids?: components["parameters"]["AccountIds"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                granularity?: components["parameters"]["Granularity"];
                group_by?: components["parameters"]["GroupBy"];
                category_keys?: components["parameters"]["CategoryKeys"];
                subcategory_keys?: components["parameters"]["SubcategoryKeys"];
                amount_min_minor?: components["parameters"]["AmountMinMinor"];
                amount_max_minor?: components["parameters"]["AmountMaxMinor"];
                kinds?: components["parameters"]["Kinds"];
                include_non_spend?: components["parameters"]["IncludeNonSpend"];
                net_refunds?: components["parameters"]["NetRefunds"];
                search?: components["parameters"]["Search"];
                currency?: components["parameters"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRow"][];
                };
            };
        };
    };
    getAnalyticsTimeseries: {
        parameters: {
            query?: {
                user_ids?: components["parameters"]["UserIds"];
                account_ids?: components["parameters"]["AccountIds"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                granularity?: components["parameters"]["Granularity"];
                group_by?: components["parameters"]["GroupBy"];
                category_keys?: components["parameters"]["CategoryKeys"];
                subcategory_keys?: components["parameters"]["SubcategoryKeys"];
                kinds?: components["parameters"]["Kinds"];
                include_non_spend?: components["parameters"]["IncludeNonSpend"];
                net_refunds?: components["parameters"]["NetRefunds"];
                currency?: components["parameters"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRow"][];
                };
            };
        };
    };
    getTopMerchants: {
        parameters: {
            query?: {
                user_ids?: components["parameters"]["UserIds"];
                account_ids?: components["parameters"]["AccountIds"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                category_keys?: components["parameters"]["CategoryKeys"];
                currency?: components["parameters"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMerchantRow"][];
                };
            };
        };
    };
    getTaxonomy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    approveSubcategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subcategory"];
                };
            };
        };
    };
    mergeSubcategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subcategory"];
                };
            };
        };
    };
    listIssuers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issuer"][];
                };
            };
        };
    };
    createIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IssuerCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issuer"];
                };
            };
        };
    };
    deleteIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateIssuer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IssuerUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issuer"];
                };
            };
        };
    };
    listLayoutSpecs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpec"][];
                };
            };
        };
    };
    createLayoutSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LayoutSpecCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpec"];
                };
            };
        };
    };
    reviseLayoutSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LayoutSpecCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpec"];
                };
            };
        };
    };
    approveLayoutSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutSpec"];
                };
            };
        };
    };
    exportLayoutSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-yaml": string;
                };
            };
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    putSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    testLlmSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestLlmResponse"];
                };
            };
        };
    };
    exportTransactions: {
        parameters: {
            query?: {
                format?: "csv" | "json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
        };
    };
}
