import type { ColumnSpec, LayoutSpecObject } from "./spec-types";

/**
 * Generates a **synthetic** fixture from a layout spec — fabricated merchant names, dates and
 * amounts laid out at the spec's own column x-bands, never anything from the real statement
 * (§2d.2 step 3: "a synthetic fixture generated from it — never the real statement").
 *
 * The output is plain text with words placed by character column (roughly proportional to each
 * column's `x0`/`x1` in PDF points), meant as a **starting point** for a developer turning this
 * into a real `tests/fixtures/generated/*` case — not itself an `ExtractedDoc` and not run by
 * anything in this app. Building an actual word-coordinate `ExtractedDoc` fixture is out of this
 * screen's reach: see this WP's report for the missing API surface (statement word/coordinate
 * data) that would let the mapper preview or export something closer to the real thing.
 */

const SYNTHETIC_MERCHANTS = ["EXAMPLE MERCHANT A", "EXAMPLE MERCHANT B", "EXAMPLE MERCHANT C"];
const SYNTHETIC_AMOUNTS_MINOR = [1299, 4550, 899];

function placeAtColumn(line: string[], col: ColumnSpec, text: string, scale: number): void {
  const startChar = Math.max(0, Math.round(col.x0 * scale));
  for (let i = 0; i < text.length; i += 1) {
    line[startChar + i] = text[i] ?? " ";
  }
}

function widestX1(columns: readonly ColumnSpec[]): number {
  return columns.reduce((max, c) => Math.max(max, c.x1), 1);
}

function formatSyntheticDate(format: string, dayOffset: number): string {
  const day = String(1 + dayOffset).padStart(2, "0");
  if (format.includes("%Y")) return format.replace("%m", "01").replace("%d", day).replace("%Y", "2024");
  return format.replace("%m", "01").replace("%d", day);
}

function formatSyntheticMoney(amountMinor: number): string {
  return (amountMinor / 100).toFixed(2);
}

function buildRow(spec: LayoutSpecObject, index: number, scale: number): string {
  const width = Math.round(widestX1(spec.columns) * scale) + 20;
  const line: string[] = new Array<string>(width).fill(" ");

  for (const col of spec.columns) {
    if (col.type === "date" && col.name === "posted_date") {
      const fmt = col.formats?.[0] ?? "%m/%d";
      placeAtColumn(line, col, formatSyntheticDate(fmt, index), scale);
    } else if (col.name === "description") {
      placeAtColumn(line, col, SYNTHETIC_MERCHANTS[index % SYNTHETIC_MERCHANTS.length] ?? "EXAMPLE MERCHANT", scale);
    } else if (col.type === "money") {
      placeAtColumn(line, col, formatSyntheticMoney(SYNTHETIC_AMOUNTS_MINOR[index % SYNTHETIC_AMOUNTS_MINOR.length] ?? 1000), scale);
    } else if (col.type === "text" && col.name === "issuer_category") {
      placeAtColumn(line, col, "MERCHANDISE", scale);
    }
  }
  return line.join("").replace(/\s+$/, "");
}

/**
 * Builds a fabricated statement's plain text and its own layout spec side by side, as a two-part
 * text export: `--- spec.yaml ---` then the spec text, `--- fixture.txt ---` then a few synthetic
 * rows laid out at the spec's column bands plus its section headings and terminator (when
 * declared). Every value is invented; nothing here can carry real statement data because nothing
 * from a real statement is ever passed to this function.
 */
export function generateSyntheticFixture(spec: LayoutSpecObject, specYaml: string): string {
  const maxX1 = widestX1(spec.columns);
  const scale = maxX1 > 0 ? Math.min(1, 90 / maxX1) : 1;

  const lines: string[] = [];
  const heading = spec.sections?.patterns?.[0]?.match;
  if (heading) lines.push(heading);
  for (let i = 0; i < 3; i += 1) {
    lines.push(buildRow(spec, i, scale));
  }
  const terminator = spec.sections?.terminator;
  if (terminator && !/[.*+?^${}()|[\]\\]/.test(terminator)) lines.push(terminator);

  return [
    "# Synthetic fixture generated by the layout mapper (§2d.2) — fabricated data only,",
    "# never content from a real statement. Adapt into a real ExtractedDoc-based test fixture",
    "# under tests/fixtures/generated/ before contributing it upstream.",
    "",
    "--- spec.yaml ---",
    specYaml.trimEnd(),
    "",
    "--- fixture.txt ---",
    ...lines,
    "",
  ].join("\n");
}
